"""remove_enable_contextual_retrieval

Revision ID: 26af9e7bf002
Revises: 8538530e6fac
Create Date: 2026-06-03 02:10:29.160909
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26af9e7bf002'
down_revision: str | None = '8538530e6fac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_configs', 'enable_contextual_retrieval')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_configs', sa.Column('enable_contextual_retrieval', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
