"""add_rating_to_chat_message

Revision ID: 2b290a135f69
Revises: 26af9e7bf002
Create Date: 2026-06-04 01:23:40.670061
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b290a135f69'
down_revision: str | None = '26af9e7bf002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('rating', sa.String(length=20), nullable=True))
    op.add_column('chat_messages', sa.Column('rating_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'rating_reason')
    op.drop_column('chat_messages', 'rating')
    # ### end Alembic commands ###
