"""remove_department_is_active

Revision ID: 5afc0340c68f
Revises: c14d087a065c
Create Date: 2026-07-07 03:55:58.797083
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5afc0340c68f'
down_revision: str | None = 'c14d087a065c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
