"""add_department_kb_overrides

Revision ID: c14d087a065c
Revises: 644935d43f66
Create Date: 2026-06-08 03:34:28.384618
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c14d087a065c'
down_revision: str | None = '644935d43f66'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_kb_overrides',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('department_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('override_type', postgresql.ENUM('allow', 'deny', name='overridetype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('knowledge_gaps')
    op.drop_column('rag_configs', 'enable_query_rewrite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_configs', sa.Column('enable_query_rewrite', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('knowledge_gaps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='knowledge_gaps_pkey')
    )
    op.drop_table('department_kb_overrides')
    # ### end Alembic commands ###
